name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"
 
[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.vars]
CUSTOM_DOMAIN = "p.diedye.org.es"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"

[env.production]
name = "cloudflare-docker-proxy"
 routes = [
   { pattern = "docker.p.diedye.org.es", custom_domain = true },
   { pattern = "quay.p.diedye.org.es", custom_domain = true },
   { pattern = "gcr.p.diedye.org.es", custom_domain = true },
   { pattern = "k8s-gcr.p.diedye.org.es", custom_domain = true },
   { pattern = "k8s.p.diedye.org.es", custom_domain = true },
   { pattern = "ghcr.p.diedye.org.es", custom_domain = true },
   { pattern = "cloudsmith.p.diedye.org.es", custom_domain = true },
 ]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
# route = { pattern = "docker-staging.libcuda.so", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
